# Config used by spark engine. Chose selection by passing the key with flag, e.g. --base_config_key econ
configs:
  test:
    spark.executor.memory: 1g
    spark.driver.memory: 1g
    spark.executor.cores: 2

  econ:
    spark.executor.memory: 2g
    spark.driver.memory: 2g
    spark.executor.cores: 2

  medium:
    spark.executor.memory: 3g
    spark.driver.memory: 3g
    spark.executor.cores: 4
