# Basic config executable for processing both Russian and Ukrainian losses from Oryx, based on longrow input

pipeline: "Oryx losses full default"
tasks:
  - class: OryxLossesSummary
    out: summary
    steps: etl
    metadata:
      generated:
      - column: as_of
        method: date_from_filename
      - column: conflict
        method: resolve_from_filename
        args:
          attack-on-europe: "Russo-Ukrainian War"
      - column: party
        method: resolve_from_filename
        args:
          attack-on-europe-documenting-equipment: "Russia"
          attack-on-europe-documenting-ukrainian: "Ukraine"

  - class: OryxLossesItem
    out: item
    steps: etl
    metadata:
      generated:
      - column: as_of
        method: date_from_filename
      - column: conflict
        method: resolve_from_filename
        args:
          attack-on-europe: "Russo-Ukrainian War"
      - column: party
        method: resolve_from_filename
        args:
          attack-on-europe-documenting-equipment: "Russia"
          attack-on-europe-documenting-ukrainian: "Ukraine"

  - class: OryxLossesProofs
    out: proofs
    steps: etl
    metadata:
      generated:
      - column: conflict
        method: resolve_from_filename
        args:
          attack-on-europe: "Russo-Ukrainian War"
