# Basic config executable for processing both Russian and Ukrainian losses from Oryx, based on longrow input

pipeline: "Oryx losses full - default"
tasks:
  - class: OryxLossesSummary
    table: summary
    steps: etl
    metadata:
      generated:
      - column: as_of
        method: date_from_filename
      - column: conflict
        method: resolve_from_filename
        args:
          attack-on-europe: "Russo-Ukrainian_War"
      - column: party
        method: resolve_from_filename
        args:
          attack-on-europe-documenting-equipment: "Russia"
          attack-on-europe-documenting-ukrainian: "Ukraine"

  - class: OryxLossesProofs
    table: proofs
    steps: etl
    metadata:
      generated:
      - column: conflict
        method: resolve_from_filename
        args:
          attack-on-europe: "Russo-Ukrainian_War"

  - class: OryxLossesItem
    table: loss_item
    steps: etl
    metadata:
      generated:
      - column: as_of
        method: date_from_filename
      - column: conflict
        method: resolve_from_filename
        args:
          attack-on-europe: "Russo-Ukrainian_War"
      - column: party
        method: resolve_from_filename
        args:
          attack-on-europe-documenting-equipment: "Russia"
          attack-on-europe-documenting-ukrainian: "Ukraine"
