tables:

  summary:
    columns:
      start_date:
        type: TEXT
      stop_date:
        type: TEXT
      conflict:
        type: TEXT
      party:
        type: TEXT
      category_name:
        type: TEXT
      destroyed:
        type: INTEGER
      damaged:
        type: INTEGER
      abandoned:
        type: INTEGER
      captured:
        type: INTEGER
      total:
        type: INTEGER

  proofs:
    columns:
      id:
        type: INTEGER
        auto_inc_primary_key: true
      proof:
        type: TEXT
        unique: true

  loss_item:
    columns:
      start_date:
        type: TEXT
      stop_date:
        type: TEXT
      conflict:
        type: TEXT
      party:
        type: TEXT
      category_id:
        type: INTEGER
      type_name:
        type: TEXT
      loss_id:
        type: INTEGER
      loss_type:
        type: TEXT
      proof_id:
        type: INTEGER
    foreign_keys:
      - column: proof_id
        references_table: proofs
        references_column: id

  category_names:
    columns:
      id:
        type: INTEGER
        auto_inc_primary_key: true
      category:
        type: TEXT
        unique: true

indexes:
  idx_item_start_date:
    table: loss_item
    columns:
      - start_date

  idx_item_stop_date:
    table: loss_item
    columns:
      - stop_date

  idx_item_category:
    table: loss_item
    columns:
      - category_name

  idx_item_type:
    table: loss_item
    columns:
      - type_name

  idx_item_loss:
    table: loss_item
    columns:
      - loss_type
